[versions]
agp = "8.9.2"
kotlin = "2.1.20"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library" }
maven-publish = { id = "com.vanniktech.maven.publish", version = "0.31.0" }